# Generated by Django 3.0.8 on 2020-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200908_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('candidate_address', models.CharField(max_length=100)),
                ('candidate_query', models.CharField(max_length=500)),
                ('candidate_photo', models.CharField(max_length=500)),
            ],
        ),
    ]
