# Generated by Django 3.0.8 on 2020-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_password', models.CharField(max_length=100)),
                ('v_username', models.CharField(max_length=100)),
                ('v_name', models.CharField(max_length=100)),
                ('v_email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('voter_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('copy', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
