# Generated by Django 3.0.8 on 2020-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20200916_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bjp', models.CharField(max_length=10000)),
                ('sp', models.CharField(max_length=10000)),
                ('congress', models.CharField(max_length=10000)),
                ('bsp', models.CharField(max_length=10000)),
            ],
        ),
    ]
