# Generated by Django 3.0.8 on 2020-09-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_cast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='Voting',
        ),
    ]
