# Generated by Django 3.0.8 on 2020-09-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20200917_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voting',
            new_name='Cast',
        ),
    ]
