# Generated by Django 3.0.8 on 2020-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20200917_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bjp', models.CharField(max_length=10000)),
                ('sp', models.CharField(max_length=10000)),
                ('cong', models.CharField(max_length=10000)),
                ('bsp', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
