# Generated by Django 3.0.2 on 2021-03-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20200917_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
